title: Esteban Martínez Hernández 
description : This site is a Portfolio of my BS degree studying Nanotechnology at Tec de Monterrey
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
